var myVariable ='Namaste';
console.log (myVariable, typeof myVariable);
myVariable =1000;
console.log (myVariable, typeof myVariable);
myVraiable =true;
console.log (myVariable, typeof myVariable);
myVariable =null;
console.log (myVariable, typeof myVariable);
myVariable =undefined;
console.log (myVariable, typeof myVariable);
